packages:
    - "web"
    - "frontend-core"

catalogMode: prefer

overrides:
    vite: "catalog:"
    vitest: "catalog:"

peerDependencyRules:
    allowAny:
        - vite
        - vitest
    allowedVersions:
        vite: "*"
        vitest: "*"

allowBuilds:
    "@parcel/watcher": true

catalog:
    "@ant-design/cli": ^6.5.0
    "@ant-design/icons": ^6.3.2
    "@ant-design/pro-components": 3.1.12-0
    "@cap.js/wasm": ^0.0.7
    "@tanstack/react-query": ^5.101.2
    "@testing-library/jest-dom": ^6.9.1
    "@testing-library/react": ^16.3.2
    "@types/react": ^19.2.17
    "@types/react-dom": ^19.2.3
    "@babel/core": ^8.0.0-rc.6
    "@rolldown/plugin-babel": ^0.2.3
    "@types/babel__core": ^7.20.5
    "@types/node": 24.13.3
    "@vitejs/plugin-react": ^6.0.3
    babel-plugin-react-compiler: ^1.0.0
    antd: ^6.5.0
    axios: ^1.18.1
    cap-widget: ^0.1.56
    dayjs: ^1.11.19
    jsdom: ^29.1.1
    keepalive-for-react: ^5.0.11
    keepalive-for-react-router: ^5.0.7
    react: ^19.2.7
    react-dom: ^19.2.7
    react-router: ^8.2.0
    vite: "npm:@voidzero-dev/vite-plus-core@0.2.4"
    vite-plus: 0.2.4
    vitest: 4.1.10
    zod: ^4.4.3
    zustand: ^5.0.14

patchedDependencies:
    cap-widget@0.1.56: patches/cap-widget@0.1.56.patch
