catalogMode: prefer

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vitest: "npm:@voidzero-dev/vite-plus-test@latest"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

allowBuilds:
  "@parcel/watcher": true

catalog:
  "@cap.js/widget": ^0.1.56
  element-plus: ^2.14.2
  vite-plugin-vue-devtools: ^8.1.2
  vue: ^3.5.38
