-- Spring Session JDBC 4.0.3
-- Source: org/springframework/session/jdbc/schema-postgresql.sql

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

comment on table SPRING_SESSION is 'Spring Session 会话主表';
comment on column SPRING_SESSION.PRIMARY_ID is '会话记录主键';
comment on column SPRING_SESSION.SESSION_ID is '对外会话 ID';
comment on column SPRING_SESSION.CREATION_TIME is '会话创建时间，Unix 毫秒';
comment on column SPRING_SESSION.LAST_ACCESS_TIME is '最后访问时间，Unix 毫秒';
comment on column SPRING_SESSION.MAX_INACTIVE_INTERVAL is '最大空闲间隔，单位秒';
comment on column SPRING_SESSION.EXPIRY_TIME is '会话过期时间，Unix 毫秒';
comment on column SPRING_SESSION.PRINCIPAL_NAME is '登录主体名称';

comment on table SPRING_SESSION_ATTRIBUTES is 'Spring Session 会话属性表';
comment on column SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID is '关联 SPRING_SESSION.PRIMARY_ID';
comment on column SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME is '会话属性名';
comment on column SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES is '序列化后的会话属性值';
